steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/it-auth-service:$COMMIT_SHA",
        "-t",
        "gcr.io/$PROJECT_ID/it-auth-service:latest",
        ".",
      ]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/it-auth-service:$COMMIT_SHA"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/it-auth-service:latest"]

  # Deploy to Cloud Run (staging)
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # Deploy to Cloud Run using gcloud run deploy
        gcloud run deploy it-auth-service-staging \
          --image=gcr.io/$PROJECT_ID/it-auth-service:$COMMIT_SHA \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated \
          --port=8080 \
          --set-env-vars="ENVIRONMENT=test,LOG_LEVEL=info" \
          --set-secrets="JWT_SECRET=it-chatbot-jwt-password:latest,DB_PASSWORD=it-chatbot-db-password:latest" \
          --cpu=1 \
          --memory=512Mi \
          --min-instances=1 \
          --max-instances=10 \
          --concurrency=100 \
          --timeout=300

  # Deploy to Cloud Run (production) - only on main branch
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [ "$BRANCH_NAME" = "main" ] || [ "$BRANCH_NAME" = "master" ] || [ -z "$BRANCH_NAME" ]; then
          echo "Deploying to production..."
          # Deploy to Cloud Run using gcloud run deploy
          gcloud run deploy it-auth-service \
            --image=gcr.io/$PROJECT_ID/it-auth-service:$COMMIT_SHA \
            --region=us-central1 \
            --platform=managed \
            --allow-unauthenticated \
            --port=8080 \
            --set-env-vars="ENVIRONMENT=production,LOG_LEVEL=warn" \
            --set-secrets="JWT_SECRET=it-chatbot-jwt-password:latest,DB_PASSWORD=it-chatbot-db-password:latest" \
            --cpu=1 \
            --memory=512Mi \
            --min-instances=2 \
            --max-instances=100 \
            --concurrency=100 \
            --timeout=300
        else
          echo "Skipping production deployment - branch: $BRANCH_NAME (not main/master)"
          exit 0
        fi

# Store images in Container Registry
images:
  - "gcr.io/$PROJECT_ID/it-auth-service:$COMMIT_SHA"
  - "gcr.io/$PROJECT_ID/it-auth-service:latest"

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  # machineType: 'E2_HIGHCPU_8'

# Timeout for the entire build
timeout: "1200s"

# Substitutions (variables)
substitutions:
  _REGION: "us-east1"
  # _PROJECT_ID: '$PROJECT_ID'
